name: CI - Compilar Código

on:
  pull_request:
  push:
    branches: ["main","master"]   # Ao realizar push no github, ele irá rodar o que tem nos jobs

jobs:
  build:
    runs-on: ubuntu-latest        # Na ultima versão do ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar GCC e NCurses
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libncurses-dev

      - name: Compilar Código
        run: make